### ISSUE TITLE
Flexible strip height does not scale along w. volume

### ISSUE THREAD

**Issue by practicingruby** [PracticingDeveloper/dentaku-zen-garden#3]
Three possible fixes:
1. Make strip height dynamic... so instead of "1x6 wood strip", we'd have "1 inch thick wood strip" and then figure out quantity by length x height
2. Make height a fixed value (i.e. hardcode it to 6 inches)
3. Make height defined by the kind of strip used in a project.

I kind of like option #3, but no idea if that's complicated or not. Thoughts @rubysolo?

**Comment by rubysolo** [comment]
Would option 1 essentially change the measurement unit from linear to square?  That could work.

Otherwise, we could bake into the formula to multiply the length by (garden height / strip material height) -- (assuming ideal materials!) a 3cm tall garden could be made with half the length of 6cm tall strip, a 9cm tall garden could be made with 1.5x the length, etc.

wdyt?

**Comment by practicingruby** [comment]
Option 1 would change the measurement unit to square, yes.

I think assuming that strips can be cut and stacked is a bit too unrealistic, even if it makes the numbers work. Pulling the height dimension from the strip type (i.e. we could make the wooden strip 1x6 and the flexible strip 1x4 to illustrate the difference) is most appealing, because then basically the material used would determine the height dimension.

But is that something difficult to represent as a rule? Having trouble wrapping my head around how to model that (beyond hard coding a garden height, which isn't really what I want)

**Comment by practicingruby** [comment]
On closer thought... unless constraining the garden height by the strip height would lead to some clever formulas that would add value to the article, Option 1 (specifying both length and height for strips) seems to be the easiest to implement, and the easiest to understand.

**Comment by rubysolo** [comment]
Agreed.
